### ISSUE TITLE
Can't build - fails on setup.py

### ISSUE THREAD

**Issue by jenka13all** [MarkusSagen/Master-Thesis-Multilingual-Longformer#3]
When running "make build && make up", the build fails on setup.py, which lists "lib" and "tracking" as packages. There is a "tracking" directory in "src", but no "lib" directory, and that seems to be the problem. What's the recommended fix for this? Is "lib" supposed to be external? Can this part of the setup.py be removed?

**Comment by MarkusSagen** [comment]
Great for pointing it out. They are no longer needed, and made the installation process more cumbersome. The latest commit should have removed those from the setup process

**Comment by jenka13all** [comment]
Thanks - that was fast!
